### ISSUE TITLE
TypeError: a bytes-like object is required, not 'dbus.Array'

### ISSUE THREAD

**Issue by Kiy4h** [sugarlabs/sugar-datastore#20]
When running the activity, after a few plays, I got this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 607, in msg_reply_handler
    *message.get_args_list()))
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 838, in __save_error_cb
    err)
RuntimeError: Error saving activity object to datastore: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.7/dist-packages/carquinyol/datastore.py", line 365, in update
    self._metadata_store.store(uid, props)
  File "/usr/lib/python3.7/dist-packages/carquinyol/metadatastore.py", line 25, in store
    self._set_property(uid, key, value, md_path=metadata_path)
  File "/usr/lib/python3.7/dist-packages/carquinyol/metadatastore.py", line 63, in _set_property
    f.write(value)
TypeError: a bytes-like object is required, not 'dbus.Array'
```

This is a bug and is probably able to be fixed.

**Comment by quozl** [comment]
Mastermind activity is unusual in that it stores a `dict` and a `list` in the journal object metadata.

Same problem _TypeError: a bytes-like object is required, not 'dbus.Dictionary'_ can be reproduced without using an activity by hacking on the `copy-to-journal` program to store a `dict` in the journal object metadata;

```diff
--- a/bin/copy-to-journal
+++ b/bin/copy-to-journal
@@ -86,15 +86,13 @@ if __name__ == "__main__":
             tag_string = " ".join(args.tag_list)
             entry.metadata['tags'] = tag_string
 
+        test = {0: [-1, -1], 1: [-1, -1], 2: [-1, -1]}
+        entry.metadata['balls'] = test
+
         datastore.write(entry)
         print('Created as %s' % (entry.object_id))
 
         entry.destroy()
 
-    except DBusException:
-        print('ERROR: Unable to connect to the datastore.\n'
-              'Check that you are running in the same environment as the '
-              'datastore service.')
-
     except Exception as e:
         print('ERROR: %s' % (e))
```

**Comment by quozl** [comment]
Using the Python 2 release of Datastore, branched from tag v0.113, with the same reproducer completes without error.

```
--- a/bin/copy-to-journal
+++ b/bin/copy-to-journal
@@ -86,15 +86,13 @@ if __name__ == "__main__":
             tag_string = " ".join(args.tag_list)
             entry.metadata['tags'] = tag_string
 
+        test = {0: [-1, -1], 1: [-1, -1], 2: [-1, -1]}
+        entry.metadata['balls'] = test
+
         datastore.write(entry)
         print 'Created as %s' % (entry.object_id)
 
         entry.destroy()
 
-    except DBusException:
-        print 'ERROR: Unable to connect to the datastore.\n'\
-              'Check that you are running in the same environment as the '\
-              'datastore service.'
-
     except Exception, e:
         print 'ERROR: %s' % (e)
```

So regression was introduced by 9e21c0a ("Port to Python 3").

**Comment by quozl** [comment]
Mastermind activity has used a behaviour of the Datastore that was not documented, and was not properly implemented.  The Datastore in Python 2 was not transparent for data types other than `str` and `int`.  When given a `dict` or `list`, the Datastore used `str` to convert to string, and when asked to return the value did return a `str` containing a Python representation of the data, instead of a `dict` or `list`.

See the use of `eval` in https://github.com/sugarlabs/mastermind-activity/blob/master/activity.py#L113

By using `eval`, Mastermind activity worked around the non-transparent behaviour of the Datastore for these unsupported data types.

Dasher, by the same author, is another activity that uses `eval` on metadata returned by the Datastore.
https://github.com/sugarlabs/dasher-activity/blob/master/keyboard.py#L491

My opinion is that the Datastore should not be expected to store any data type, and we should instead fix the activities to use some form of string encoding, such as JSON.  Opinions please?

**Comment by quozl** [comment]
@cristian99garcia, mentioning you as author of Mastermind and Dasher.  You used a behaviour of Datastore that broke with our port to Python 3, and we're thinking about what to do about it.  You're welcome to comment.

**Comment by quozl** [comment]
https://github.com/cristian99garcia/mastermind-activity/pull/4

**Comment by chimosky** [comment]
@quozl said
> My opinion is that the Datastore should not be expected to store any data type, and we should instead fix the activities to use some form of string encoding, such as JSON. Opinions please?

Agreed as it's an API and doesn't need to handle certain things that can be handled in a way favourable to the API's existing feature, it also creates a uniformity as activities can store any arbitrary type of data as long as it follows the API standard.
