### ISSUE TITLE
No journal entries

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/sugar-datastore#25]
I'd noticed recently that after running sugar I couldn't view any items in the journal with a `Your Journal is Empty` screen and no new activity instance is stored either and the logs show this, haven't debugged further to figure out why this is happening.

@quozl any ideas?

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/listmodel.py", line 256, in do_iter_next
    if idx >= self._result_set.length:
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 112, in get_length
    entries, self._total_count = self.find(query)
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 226, in find
    byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.7/dist-packages/carquinyol/datastore.py", line 409, in find
    metadata = self._metadata_store.retrieve(uid, properties)
  File "/usr/lib/python3.7/dist-packages/carquinyol/metadatastore.py", line 84, in retrieve
    metadata[key] = dbus.Int32(value)
ValueError: invalid literal for int() with base 10: b''
```

**Comment by quozl** [comment]
Python 3.7?  What operating system and Sugar version is that?

**Comment by quozl** [comment]
Okay, looking at the traceback and the source, this is during retrieve
of metadata from the store on disk.

So go through the store by hand using shell commands and see if you
can find a filesize, creation_time, or timestamp containing b''
instead of a number.

Then check the date the metadata file was created, and if the date was
within a range of when you were using buggy datastore code, i.e. prior
to fixing known problems, then you've got a case of infected store.

Fix the store by hand using an editor, or destroy the store and test
again.

Destroying it is tempting, but doesn't solve the question of how the
store got into this state to begin with.

Then try to reproduce the problem with a fixed store.  If something is
causing the b'' to be written, it needs to be found and fixed.
